// Generated by https://quicktype.io

export interface Genre {
    movies:       null;
    genres:       GenreElement[];
    rating:       null;
    casts:        null;
    trailers:     null;
    trailer:      null;
    totalItemNum: number;
    currentPage:  number;
    genreId:      number;
}

export interface GenreElement {
    movieId:        number;
    revenue:        number;
    genreId:        number;
    genreName:      null;
    movieTitle:     string;
    moviePosterUrl: string;
    pages:          number;
    rating:         number;
}
