// Generated by https://quicktype.io

export interface Purchase {
    userId:           number;
    purchaseNumber:   string;
    totalPrice:       number;
    purchaseDateTime: string;
    movieId:          number;
    moviePosterUrl:   string;
    movies:           any[];
}
