// Generated by https://quicktype.io

export interface User {
    nameid:      string;
    email:       string;
    given_name:  string;
    family_name: string;
    birthdate:   string;
    nbf:         number;
    exp:         number;
    iat:         number;
    iss:         string;
    aud:         string;
}
